# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatchet" do
  version "0.86.32"

  on_macos do
    on_intel do
      sha256 "1a9e869b97adf265fb3924ddf7a8d6bc1b3a33cd2b18d0c6b65b4454baf668b1"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6b4442313bdf2cfb3d3f339216407adcf035aa17a57579eb999ef07536ddcdfb"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "45c6d1a66cb6f0c94f3518c0b6dbb79294bbfc4a64aac0528f66ba68e9f5c644"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bcbad861639f3ee9475b9725309372925cfda37484e49a978c1c30fcd2a1d6d"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "hatchet"
  desc "Command-line interface for Hatchet workflow orchestration"
  homepage "https://hatchet.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatchet"

  # No zap stanza required

end
