# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatchet" do
  name "hatchet"
  desc "Command-line interface for Hatchet workflow orchestration"
  homepage "https://hatchet.run"
  version "0.78.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatchet"

  on_macos do
    on_intel do
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_x86_64.tar.gz"
      sha256 "e92f7af9fe1473d127ca0bb6f29f5d55e20a0ab8719bad29b963626f048a35fa"
    end
    on_arm do
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_arm64.tar.gz"
      sha256 "d018ece3b1b2375bbe10b454d60a3faade6144b0316c93ab0aacd426fb772611"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_x86_64.tar.gz"
      sha256 "e83aa8accaf7722fa0170c3823013147b02e8c0260c1b486339df7cd71b8cb75"
    end
    on_arm do
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_arm64.tar.gz"
      sha256 "c00b9b5224d970961be2059cfcc0962c55607c5e39e656dacea31a78c2b8a12d"
    end
  end

  # No zap stanza required
end
