# This file was generated by GoReleaser. DO NOT EDIT.
cask "hatchet" do
  version "0.86.18"

  on_macos do
    on_intel do
      sha256 "8a19ef6e00d9862fba5fe6829b55d9632c0dba2672c515437c9d99f8868fa9a5"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "a46d65d7cdec767fa13c351f682b0f86aae570ac22af3afc0de22b7d37e885a7"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6e568ebbc13e17818376ea5f4dc463955ec27c6a76ba9e99cb241c7f4cc15700"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "12396f5cd249b8ea6709ec43d41622218cfe4cb2527c2d7fd4748b8651caa32e"
      url "https://github.com/hatchet-dev/hatchet/releases/download/v#{version}/hatchet_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "hatchet"
  desc "Command-line interface for Hatchet workflow orchestration"
  homepage "https://hatchet.run"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hatchet"

  # No zap stanza required

end
