# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hatchet < Formula
  desc "Command-line interface for Hatchet workflow orchestration"
  homepage "https://hatchet.run"
  version "0.74.15-alpha.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hatchet-dev/hatchet/releases/download/v0.74.15-alpha.1/hatchet_0.74.15-alpha.1_Darwin_x86_64.tar.gz"
      sha256 "80a79f1fec7b805899dd84448ce36757b2b1bed0c0209c8a41085dfd5003092a"

      def install
        bin.install "hatchet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hatchet-dev/hatchet/releases/download/v0.74.15-alpha.1/hatchet_0.74.15-alpha.1_Darwin_arm64.tar.gz"
      sha256 "9c8f67f327dea5d17155479827a67a8d6d74128f7bd374511ce011c316afb3e5"

      def install
        bin.install "hatchet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hatchet-dev/hatchet/releases/download/v0.74.15-alpha.1/hatchet_0.74.15-alpha.1_Linux_x86_64.tar.gz"
      sha256 "1a889cb9f6efac7ce6ee1ac13b22daf689a786179340cef90fe9358588e9e961"
      def install
        bin.install "hatchet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hatchet-dev/hatchet/releases/download/v0.74.15-alpha.1/hatchet_0.74.15-alpha.1_Linux_arm64.tar.gz"
      sha256 "82fc55651ae4c43841d229b504209584f6b1ca25c439eb65942ca52c65987f6b"
      def install
        bin.install "hatchet"
      end
    end
  end

  test do
    system "#{bin}/hatchet version"
  end
end
